version: '3'

services:
  app:
    build: ./app
    container_name: my_flask
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    # depends_on: node-exporter
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    # depends_on: prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
